# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f2ad52dab15db6e5b46022e67ddb64d31e6e14abd9f84003ac8a6ae8dc79d371a7d5f4c39463312ac9819132b1ceef4ae2d87cee9465f796204e5fc0da0d08a

test:
  secret_key_base: d97f9998b6b9377394014ff3d98f6746fa5ff6d889892c8b780039d37a7d7b21aea96c9670a889be00fda6396a6d14c7e5cff2b091ac775e2ffe219c8fd15cd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
